name: nefta_sdk_flutter_example
description: "Demonstrates how to use the nefta_sdk_flutter plugin."
publish_to: 'none'
version: 4.3.2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  applovin_max: any
  nefta_sdk_flutter: any

  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "icon.png"