name: nefta_sdk_flutter
description: "Nefta SDK for flutter projects."
version: 4.4.0
homepage: "https://nefta.io"

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  applovin_max: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.nefta.sdk
        pluginClass: Nefta
      ios:
        pluginClass: Nefta